language: php

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - echo "extension=zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --prefer-source

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpunit -c phpunit-functional.xml.dist
