language: php

sudo: false

cache:
  directories:
    - $HOME/.composer

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'

before_script:
  - phpenv config-rm xdebug.ini
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpunit -c phpunit-functional.xml.dist
