language: php

sudo: false

cache:
  directories:
    - $HOME/.composer

php:
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.2'

before_script:
  - phpenv config-rm xdebug.ini
  - sudo apt-get install php-zmq
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpunit -c phpunit-functional.xml.dist
